name: "Perl Author & Release Tests"
description: "Installs dependencies and performs author and release tests."
inputs:
  verbose:
    description: "Controls whether cpanm should be run with --verbose"
    required: false
    default: "false"
  release_test_addn:
    description: "Controls whether additional release tests should be run"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Install spell checker
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-en

    - name: Show perl version
      shell: bash
      run: perl -v

    - name: Set env variables AUTHOR_TESTING, RELEASE_TESTING* and TEST_AUTHOR.
      shell: bash
      run: |
        echo "AUTHOR_TESTING=1" >> $GITHUB_ENV
        echo "RELEASE_TESTING=1" >> $GITHUB_ENV
        echo "RELEASE_TEST_ADDN=${{ inputs.release_test_addn }}" >> $GITHUB_ENV
        echo "TEST_AUTHOR=1" >> $GITHUB_ENV

    - name: Build distribution
      shell: bash
      run: |
        perl Makefile.PL
        make manifest || true
        make dist

    - name: Install dependencies
      shell: bash
      env:
        VERBOSE: ${{ inputs.verbose }}
      run: |
        VERBOSE=$([ "$VERBOSE" == "true" ] && echo "--verbose" || echo "")
        cpanm --notest --installdeps --with-develop --with-test $VERBOSE .

    - name: Unpack distribution
      shell: bash
      run: |
        tar xzf *.tar.gz
        DISTFILE=$(ls -1t *.tar.gz | head -n1)
        echo "Found distribution: $DISTFILE"
        echo "DIST_DIR=${DISTFILE%.tar.gz}" >> $GITHUB_ENV
        tar -xzf $DISTFILE

    - name: Run tests in xt (if any)
      shell: bash
      run: |
        if [ -d xt ]; then
          echo "Perform xt tests..."
          prove -l --recurse xt
        else
          echo "No xt/ found – skip xt tests."
        fi

